services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=root'
      - 'POSTGRES_PASSWORD=root'
    volumes:
      - '~/volumes/aty/postgres:/var/lib/postgresql/data'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - '~/volumes/aty/pgadmin4:/var/lib/pgadmin4/data'
    ports:
      - "5050:80"
    restart: unless-stopped
volumes:
  postgres:
  pgadmin:
